### PR TITLE
Fix unicode test

### PR DESCRIPTION
**Pull request by typetetris**
Only do the non-ascii test, if the file system encoding
is reported as UTF-8.

Thanks for the pull request!

By raising this pull request you confirm you are licensing your contribution under all licenses that apply to this project (see LICENSE) and that you have no patents covering your contribution.

If you care, my PR preferences are at https://github.com/ndmitchell/neil#contributions, but they're all guidelines, and I'm not too fussy - you don't have to read them.

### CODE REVIEW

**Comment by typetetris** [comment]
Why not put that `-Werror=unused-imports` in `shake.cabal`. So I don't need to hit travis first?

**Comment by ndmitchell** [comment]
Thanks for the patch. Sorry for taking so long to get to it - I was travelling and am only just getting back on top of my email. I'll respond to #680 here too.

Generally I use `ghcid` with an appropriate `.ghci` file that turns on all the appropriate warnings. I find that putting warnings in `.cabal` files leads to your users seeing warnings (not what I want).

I thought the whole point about Unix file systems was they didn't really have any encoding, it was all just bytes, with only `/` being special - so you can pack UTF8 in there if you want and it's all happy? As such, what does the encoding of the file system mean? And does anyone use any other type of file names? And doesn't the rule that all Char can be UTF8 mean Shake works with everything? I'm far from an expert at Unix file paths though, being a Windows user, so keen to understand when it fails, where it fails, and if there's any way to stop it failing.

**Comment by typetetris** [comment]
First I want to point out, where shake will fail, if someone uses filenames in a non utf8 encoding.

`getFileStatus` uses `fileNameToByteString`, which assumes via `fileNameFromString`, an utf8 encoding.

In a lot of places `withFile` is used, which boils down to using
```
withFilePath fp f = getFileSystemEncoding >>= \enc -> GHC.withCString enc fp f
```
from `System.Posix.Internals` to convert filepaths from string to bytes, respecting `LC_CTYPE` (or the choice made by `setFileSystemEncoding`).

So the posix filepath (bunch of bytes) which is used to access the file system from those places simply don't match, if a non utf8 encoding is used via `LC_CTYPE`.

Sorry, that I didn't do this presentation in the ticket in the first place.

 > Generally I use `ghcid` with an appropriate `.ghci` file that turns on all the appropriate warnings. I find that putting warnings in `.cabal` files leads to your users seeing warnings (not what I want).

Ah, didn't see that. Thanks for the hint.
 
> I thought the whole point about Unix file systems was they didn't really have any encoding, it was all just bytes, with only `/` being special - so you can pack UTF8 in there if you want and it's all happy?

Correct. But you can also place any other encoding there, if you like. Unix applications usually respect the locale, meaning `LC_CTYPE` for converting file names from strings to bytes.

> As such, what does the encoding of the file system mean?

In my opinion, you just can't assume an encoding for the file system. Either respect the users choice, aka `LC_CTYPE`, or stick to a default and advertise as such.

> And does anyone use any other type of file names?

Really, I can't answer that. In my company we have a strict policy on file names ([a-z_] only, no whitespace), so there is no problem in most locales, as most are compatible on ascii.

> And doesn't the rule that all Char can be UTF8 mean Shake works with everything?

I would assume no. You have to choose an encoding for turning filepaths from strings to bytes and take the correct one, the user also uses for his sources for example.

**Comment by ndmitchell** [comment]
Thanks for the explanation, very useful!

**Pull request merged**
