### PR TITLE
Support GHC 9.0

### PR DESCRIPTION
**Pull request by ethercrow**

### CODE REVIEW

**Comment by ndmitchell** [comment]
What's the error message without this patch?

**Comment by ethercrow** [comment]
@ndmitchell looks like System.IO now exports `readFile'` that clashes with shake's one.

```
> cabal build --allow-newer
Build profile: -w ghc-9.0.0.20200925 -O1
In order, the following will be built (use -v for more details):
 - shake-0.19.2 (lib) (first run)
 - shake-0.19.2 (exe:shake) (first run)
Preprocessing library for shake-0.19.2..
Preprocessing executable 'shake' for shake-0.19.2..
Building library for shake-0.19.2..
Building executable 'shake' for shake-0.19.2..
[55 of 71] Compiling Development.Shake.Internal.Derived ( src/Development/Shake/Internal/Deriv
ed.hs, /Users/ethercrow/src/shake/dist-newstyle/build/x86_64-osx/ghc-9.0.0.20200925/shake-0.19
.2/x/shake/build/shake/shake-tmp/Development/Shake/Internal/Derived.o )

src/Development/Shake/Internal/Derived.hs:131:30: error:
    Ambiguous occurrence ‘readFile'’
    It could refer to
       either ‘System.IO.readFile'’,
              imported from ‘System.IO’ at src/Development/Shake/Internal/Derived.hs:20:1-16
           or ‘Development.Shake.Internal.Derived.readFile'’,
              defined at src/Development/Shake/Internal/Derived.hs:118:1
    |
131 | readFileLines = fmap lines . readFile'
    |                              ^^^^^^^^^
[56 of 73] Compiling Development.Shake.Internal.Derived ( src/Development/Shake/Internal/Deriv
ed.hs, /Users/ethercrow/src/shake/dist-newstyle/build/x86_64-osx/ghc-9.0.0.20200925/shake-0.19
.2/build/Development/Shake/Internal/Derived.o, /Users/ethercrow/src/shake/dist-newstyle/build/
x86_64-osx/ghc-9.0.0.20200925/shake-0.19.2/build/Development/Shake/Internal/Derived.dyn_o )

src/Development/Shake/Internal/Derived.hs:131:30: error:
    Ambiguous occurrence ‘readFile'’
    It could refer to
       either ‘System.IO.readFile'’,
              imported from ‘System.IO’ at src/Development/Shake/Internal/Derived.hs:20:1-16
           or ‘Development.Shake.Internal.Derived.readFile'’,
              defined at src/Development/Shake/Internal/Derived.hs:118:1
    |
131 | readFileLines = fmap lines . readFile'
    |                              ^^^^^^^^^
cabal: Failed to build shake-0.19.2.
Failed to build exe:shake from shake-0.19.2.

```

**Comment by ethercrow** [comment]
I was unable to run the tests locally with either GHC 9.0 or 8.10:

```
Error when running Shake build system:
  at want, called at src/Test/Command.hs:26:27 in main:Test.C
ommand
* Depends on: timeout5
  at apply1, called at src/Development/Shake/Internal/Rules/R
erun.hs:41:5 in main:Development.Shake.Internal.Rules.Rerun
* Depends on: helper/shake_helper
  at &%>, called at src/Test/Command.hs:59:5 in main:Test.Com
mand
* Depends on: helper/shake_helper shake_helper.o shake_helper
.hi
  at cmd, called at src/Test/Command.hs:61:9 in main:Test.Com
mand
* Raised the exception:
Development.Shake.cmd, system command failed
Command line: ghc --make shake_helper.hs -o helper/shake_help
er
Exit code: 1
Stderr:
shake_helper.hs:1:1: error:
    Could not find module ‘System.Time.Extra’
    Use -v (or `:set -v` in ghci) to see a list of the files
searched for.
  |
1 | import System.Time.Extra
  | ^^^^^^^^^^^^^^^^^^^^^^^^

```

I tried to run the tests via `cabal test`, should I do something else instead?

**Comment by ndmitchell** [comment]
Thanks for the patch. The fact that it compiles is a good suggestion it will be fine - I think Cabal 3 with its sandboxing has made the tests I want to write much harder sadly.

I think given that readFile' is now a thing in Haskell probably means it would be a good idea to give an alternative name to readFile' in Shake, and deprecate the old one. I'll do that tomorrow, and hopefully stand up some CI for 9.0 so we can test it. I'll look to merge everything tomorrow.

**Comment by ndmitchell** [comment]
Changed my mine - it looks like a positive change regardless, so will build on top of this. Thanks!

**Pull request merged**
