### PR TITLE
Semigroup-Monoid-Proposal changes

### PR DESCRIPTION
**Pull request by angerman**
Changes required to build against GHC HEAD.

This came up when trying to build HEAD with HEAD using hadrian.

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks!

Don’t you also need to depend on the semi group package?

**Comment by angerman** [comment]
Hi @ndmitchell, yes there's some additional CPP guards and the semigroup package missing.
(Semigroup-Monoid-Proposal)[https://prime.haskell.org/wiki/Libraries/Proposals/SemigroupMonoid] for reference. I'll try to get around updating this PR. Hopefully by the end of the week. Got a lot going on right now.

**Comment by angerman** [comment]
Alright, added the semigroup dependency. Still builds for me. For HEAD though I need to use
the following `cabal.project` file:
```
packages: ./

repository head.hackage
   url: http://head.hackage.haskell.org/
   secure: True
   root-keys: 07c59cb65787dedfaef5bd5f987ceb5f7e5ebf88b904bbd4c5cbdeb2ff71b740
              2e8555dde16ebd8df076f1a8ef13b8f14c66bad8eafefd7d9e37d0ed711821fb
              8f79fd2389ab2967354407ec852cbe73f2e8635793ac446d09461ffb99527f6e
   key-threshold: 3
```
mainly due to get other SMP patched packages.

**Comment by angerman** [comment]
```
src/Development/Shake/Command.hs:33:8:
    Could not find module `Data.Semigroup'
    It is a member of the hidden package `semigroups-0.18.3'.
    Perhaps you need to add `semigroups' to the build-depends in your .cabal file.
    Use -v to see a list of the files searched for.
```

huh?

**Comment by angerman** [comment]
So AppVeyor is happy now, but travis is not...
```
src/Development/Shake/Internal/Core/Database.hs:129:22:
    No instance for (NFData BS.ByteString)
      arising from a use of `rnf'
    Possible fix:
      add an instance declaration for (NFData BS.ByteString)
    In the expression: rnf x
    In an equation for `rnf': rnf (Loaded x) = rnf x
    In the instance declaration for `NFData Status'
neil: Failed when running system command: cabal build
```
Ok? The other failures are due to missing semigroup dependency? Did travis mess up the commit again?

**Comment by angerman** [comment]
Hmm. How do we generate this command:
```
Command: fsatrace rwm /tmp/extra-file-89302755099-1486222842950390868 -- ghc -package=base -package=binary -package=bytestring -package=deepseq -package=directory -package=extra -package=filepath -package=hashable -package=js-flot -package=js-jquery -package=primitive -package=process -package=random -package=time -package=transformers -package=unix -package=unordered-containers -package=utf8-string -c ../../src/General/ListBuilder.hs -i../../src -main-is Run.main -hide-all-packages -outputdir=. -DPORTABLE -fwarn-unused-imports
```

**Comment by ndmitchell** [comment]
Thanks! The error on GHC 7.4 was my fault, one I introduced a few days ago and hadn't yet had time to clean up. The command line you were looking for comes from `Self.Test`, and I've patched it.

**Pull request merged**
