### PR TITLE
Normalise paths reported by fsatrace, whitelist ~/.cabal and ~/Applications

### PR DESCRIPTION
**Pull request by jacereda**
With this patch the test suite passes when running under fsatrace.

### CODE REVIEW

**Comment by ndmitchell** [comment]
Awesome!

**Comment by ndmitchell** [comment]
Does fsatrace work under Linux yet? The next step is to get it working there, and turned on in the buildbot, so we can keep the test suite running under tracker.

**Comment by jacereda** [comment]
I can add the #ifdefs that I had in an older version that ran on Linux at some point if you have access to a linux box to test. Otherwise I can try to find some time at work (not this week probably) and try to test it there.

**Comment by ndmitchell** [comment]
I have a Linux VM I can try on, but I tend to just hope and submit to the Travis Linux CI service and debug it that way.

**Comment by jacereda** [comment]
Just pushed https://github.com/jacereda/fsatrace/commit/4dde001c56321359d145ce0d2ff3167c28798295

On linux you could try it as:

    env FSA_OUT=/dev/stdout LD_PRELOAD=fsatrace.so cp /bin/ls /tmp/foo

**Comment by jacereda** [comment]
Sorry, that should read FSAT_OUT.

**Pull request merged**
