### PR TITLE
restore depends in newCacheIO

### PR DESCRIPTION
**Pull request by adamse**
We had some problems where rules were not rebuilding, they used caches and this looked like a possible problem.

We're currently testing the fix...

### CODE REVIEW

**Comment by vapourismo** [comment]
One underlying issue was also that downgrading was hindered because the Shake Database was corrupted. Building with 0.19.4 also broke previous version 0.19.1.

With this fix, does the Shake database need to be purged/bumped?

**Comment by adamse** [comment]
It looks like this fixed the issue for us.

**Comment by adamse** [comment]
Ping @ndmitchell, could you confirm if I fixed something here or introduced a new problem? :)

**Comment by ndmitchell** [comment]
Thanks for this fix, and sorry it took so long to delve deep into the weeds to figure out exactly what it fixed and why - you were totally right, this was a big screw up. I've pushed a follow up which swaps the order of the arguments to addDepends (to make it consistent whether you hit the cache or have to compute it), and also a test so I don't screw this up in future.

**Comment by adamse** [comment]
Thanks :). I should've mentioned that I found the problem and fix by looking at the diff between the good and the bad version. That made it stand out quite a bit!

**Comment by adamse** [comment]
@ndmitchell could I trouble you for a hackage release with this fix in?

**Comment by ndmitchell** [comment]
Sorry @adamse that this took so incredibly long. Next time, feel free to reach out on my personal email if you've not getting a response. Things have gone crazy personal wise, but I should still manage less than a few months from fix to release...

**Pull request merged**
