### PR TITLE
Workaround the CI failures on master

### PR DESCRIPTION
**Pull request by dwijnand**

### CODE REVIEW

**Comment by ndmitchell** [comment]
Weird - running previously successful builds is now failing. I'd like to investigate the root cause a bit more - I guess the Linux environment the CI runs on has changed in some way such that something no longer works.

**Comment by dwijnand** [comment]
Yeah, makes sense to look into it more.

What are your thoughts on the Ninja comparison instead?  Do you think that something changed in Travis CI too there?  Or did Ninja get faster?

**Comment by ndmitchell** [comment]
Not sure on Ninja. I've got a script to dump the time series of how long Shake and Ninja both take and will see what I can see. Does need investigating!

**Comment by ndmitchell** [comment]
Closing in favour of https://github.com/ndmitchell/shake/issues/715 so we can track the FSATrace thing with an issue. I pinned our FSATrace version in 7ac71e2275be6c17889327f10a77267a8900dc26 which makes the CI start working again. I've raised https://github.com/ndmitchell/shake/issues/716 for the Ninja speed.

Sorry for the slow action on this and other patches. Unfortunately this CI issues meant I couldn't merge from a mobile as I lost the vital signal of whether it worked or not. I've also just started a new job, which has curtailed the time I can spend on a desktop (during the ramp up) and been on holiday 3 times in the last month. Hopefully I'll clear the queue tomorrow and then keep on top of things - thanks for all the patches.

**Comment by dwijnand** [comment]
Oh right, I didn't realise the CI build was tracking the HEAD of that repo.  Thank you for resolving that!

And don't worry about the PRs.  After my spree on Friday I looked back and felt guilty as it looked like I was DOSing you... :)

Also, Pepe mentioned (at a meetup) the new job, so I understand completely.  Good luck and perhaps I can buy you that beer one day? :)  (Actually, there's a GHC Core plugins talk tomorrow/Wednesday, if you're in London and free - https://www.meetup.com/London-Haskell/events/263644168/)

**Comment by ndmitchell** [comment]
Definitely don't feel guilty about patch volume - the more the merrier.

I'm at home today so won't be at the talk, but I'm sure we'll cross paths in the near future.

**Pull request closed without merging**
