### PR TITLE
Ulitize FilePattern library

### PR DESCRIPTION
**Pull request by eborden**
This addresses https://github.com/ndmitchell/shake/issues/550

FilePattern has been extracted to a library. Its functionality was
useful elsewhere. The library itself is dropping support for "//"
patterns, but they remain available in the `FilePattern.Legacy` module
so shake can have a slower path away from them.

The current draft of `filepattern` is here:
https://github.com/eborden/filepattern

This PR will not build until that library has been released on hackage.

### CODE REVIEW

**Comment by ndmitchell** [comment]
The first thing to do is thoroughly review the FilePattern library, which I've started doing, and have pushed a bunch of commits to https://github.com/ndmitchell/filepattern. Some of those will necessarily result in tweaks to this patch, but I'd wait until the FilePattern stuff is done first (I expect to make more tweaks this morning). There are still a few tweaks I want to make, but it looks really good. Two questions:

* Should it be `Text.FilePattern`? or `System.FilePattern`?
* I prefer to avoid "internalTest" things inside the main module, so the options are have a `Text.FilePattern.Internal` for reexporting just the test-specific bits, try to fudge it on the outside, or just compile the code multiple times - so the test doesn't depend on the source (cleanest, and usually my preference). Do you have any thoughts?

**Comment by eborden** [comment]
@ndmitchell 
1. Yeah, I wasn't sure what would be best here. It is dependent on `env` so `System` might be a better location.
2. Yup, that makes sense to me.

**Comment by ndmitchell** [comment]
To update where things are, as I wander through filepattern I'm making some improvements to it, and also taking the change to rethink certain aspects (mostly minor, but things that I don't want to put in stone while wrong). I'm hopefully under a week away from being happy with the filepattern library, and then actually flipping Shake to it shouldn't be too hard.

**Comment by ndmitchell** [comment]
I've now rewritten a lot of the `filepattern` library, so the interfaces and semantics are no longer what they were when the library left Shake. Given that the stringy things have changed in ways that will break code, but not at compile time, and that `//` patterns got deleted entirely, I'm wondering how to make the switch. My inclination is to get `filepattern` into HLint first, confirm it doesn't do anything super stupid, and then switch in Shake, with a very deliberate 0.1 bump and lots of publicity.

**Comment by eborden** [comment]
@ndmitchell that sounds like a reasonable plan. Bugs can be sussed out as users discover them in `hlint` instead of a big bang in `shake`.

**Comment by ndmitchell** [comment]
Closing this PR as given the extensive changes in `filepattern`, I don't think it's going to provide much useful benefit in the migration. The ticket #550 should definitely remain for now, until we're ready to go forward.

**Pull request closed without merging**
