### PR TITLE
Add `cmd` examples to illustrate arguments.

### PR DESCRIPTION
**Pull request by chexxor**
In the Google group thread I said I'd like to add examples of using the `cmd` function. I don't know how to preview the output of these docs. Any tips? Or perhaps it is fine with a look-over from you?

### CODE REVIEW

**Comment by ndmitchell** [comment]
It's fine with a look over from me - I'll merge it tomorrow with any luck (plus get it through my automatic documentation checks, which are fairly exacting). To test locally you can do `cabal configure && cabal haddock` then look in `dist/doc/html/shake` - although no real need.

**Comment by ndmitchell** [comment]
I probably won't get to this until tomorrow (I managed to go and get ill), but even if not tomorrow, it will be merged within a few days.

**Comment by ndmitchell** [comment]
Thanks, I've merged them in, and also tweaked the docs slightly so they work with the documentation checker.

**Comment by chexxor** [comment]
Excellent! Thanks for the help!

**Pull request merged**
