### PR TITLE
Make ** patterns not match absolute paths.

### PR DESCRIPTION
**Pull request by ezyang**
Signed-off-by: Edward Z. Yang <ezyang@cs.stanford.edu>

### CODE REVIEW

**Comment by ezyang** [comment]
I will admit, the walker test failure is positively baffling. I have no idea what walker is supposed to do.

**Comment by ndmitchell** [comment]
Discussion at #376

**Comment by ndmitchell** [comment]
Looking at the patch, I don't see it handling Windows paths, so `C:/foo` will match `**` even though it really shouldn't. I think it only makes sense for `Rel` to be at the start, and to be an immediate directory prefix test, so I might make it not part of the pattern desugaring and just do an explicit test - if `**` is a prefix then it can't be relative.

As to what relative is, I probably won't use the definition from `FilePath`, since there (on Windows) `/foo` and `C:foo` are both considered relative. In truth they aren't absolute, but they aren't fully relative either, and for this purpose I think that's "not in the current directory" so shouldn't match.

**Comment by ezyang** [comment]
It looks like you'd have to make more invasive changes to make it not match absolute paths on Windows, I agree. Having `**` not match absolute paths is no longer on the hotpath for me, since I no longer use it in my build system.

**Comment by ndmitchell** [comment]
Great, even now it's not on the hot path, do you still think it makes sense to do? My guess is it does.

As a matter of interest, could not comment on any tickets/pull-requests that are still on your hotpath?

**Comment by ezyang** [comment]
I think it still makes sense for `**` to not match absolute paths, because then it doesn't compose nicely with `</>`.

**Comment by ndmitchell** [comment]
> As a matter of interest, could not comment on any tickets/pull-requests that are still on your hotpath?

That was a typo, which almost entirely reverses the sense of the message, For clarification I meant:

As a matter of interest, could you comment on any tickets/pull-requests that are still on your hotpath?

**Comment by ndmitchell** [comment]
Looking at the code, it turned out to be way easier to just test if the pattern required relative paths, and the path was relative. I didn't merge you diff directly, but did go through and take your comments/test corrections and incorporate them. Thanks for the pull request, and sorry it took so disastrously long to get merged!

**Pull request closed without merging**
