### PR TITLE
Rename priority to preference

### LINKED ISSUE #629: priority vs deprioritise is confusing
The priority function sets the preference of which rule to pick. The deprioritise function takes a running task and reduces its execution priority. Using the same name for both is a bad idea. Should I rename one of them? Renaming deprioritise would be easier since it's newer, but not essential.

My best thought so far is to rename `priority` to `preference`, but I'm welcome to better suggestions.

### PR DESCRIPTION
**Pull request by dwijnand**
Also rename the internal Priority to Preference.

Fixes #629

This is my first Haskell contribution so if I missed something, even
something generally obvious, please let me know.  Feedback and advice
welcomed :)

### CODE REVIEW

**Comment by dwijnand** [comment]
The remaining uses of 'priority' or 'Priority' I think are fine as they either:
* refer to the other `deprioritise`/`PoolPriority` feature
* refer to something else entirely (e.g "Write a normal priority message to the output")
* shouldn't be changed (e.g. academic/icfp2012/shake.tex)

But double-check as I might've misunderstood, so I'd be happy to fix-up.

**Comment by dwijnand** [comment]
@ndmitchell seem good to you?

**Comment by ndmitchell** [comment]
Sorry for the long delay! Holidays and a new job, but I'm slowly getting on top of things.

**Comment by ndmitchell** [comment]
Only remark from the review is that I tend to deprecate things with a message first, and only 0.1-0.2 after turn on a deprecated warning. Some people run with warnings as errors, so I try and get these things done slowly, where it doesn't actually cause problems. I've tweaked that in a follow up.

**Pull request merged**
