### PR TITLE
Fix stdcall warnings on x64

### PR DESCRIPTION
**Pull request by jacereda**

### CODE REVIEW

**Comment by jacereda** [comment]
I'm not sure this is the right way to deal with this.

**Comment by ndmitchell** [comment]
I can't think of a better way, so my inclination is to merge this and consider it fixed. Looks good to me.

**Comment by jacereda** [comment]
Shouldn't the appveyor script be changed to do something like "stack --resolver=nightly-xxx"?

**Comment by jacereda** [comment]
Or maybe just add a stack.yaml...

**Comment by ndmitchell** [comment]
There is no nightly with the new version of extra - I think it should have been produced last night but it's still missing. I expected one day broken, but it's a bit annoying to have two.

**Comment by ndmitchell** [comment]
I ideally don't want to add a stack.yml because it requires maintaining, which is a bit annoying, especially if using the nightly is always expected to work.

**Comment by jacereda** [comment]
I tried with nightly-2016-01-08 and extra-1.4.3 is there.

**Comment by ndmitchell** [comment]
Ah, we aren't failing to find a build plan since nightly would work. Instead we have managed to corrupt the appveyor cache meaning the build plan has a `.git` file but no contents, which Stack then fails to update properly. Annoying, and I fixed it in Stack recently, so hopefully temporary.

**Comment by ndmitchell** [comment]
Hmm, turned out we needed something in the .hs files otherwise it doesn't work in ghci or if we runhaskell or ghc --make it (as we do in the test suite). Since the .hs files have to have an `#ifndef` they might as well define the variable themselves - so I moved it there instead of in the cabal. As it turns out we have 3 hs files that require it, instead of 3 instances in the Cabal file, so doesn't make too much difference.

**Comment by jacereda** [comment]
I guess ghc needs an `apicall`to do the right thing in each platform or something like that.

**Comment by ndmitchell** [comment]
That would be very useful!

**Pull request merged**
