### PR TITLE
Handle exceptions in --share-list and --share-remove

### PR DESCRIPTION
**Pull request by pepeiborra**
Our shared caches seem to work fine, but these commands fail with errors like "couldn't find map for "FileQ {...}". I want the commands to work despite the bad entries.

### CODE REVIEW

**Comment by ndmitchell** [comment]
Thanks, definitely want to have some catching of exceptions around this code, or you will get stuck with a cache you can't clean. Why not just catch all exceptions (or all those which are syncronous - see isAsyncException to test)?

**Comment by pepeiborra** [comment]
That’s right, cleaning the cache while changing a rule is often required. 
Will update the PR to catch all synchronous exceptions tonight, although it seems a bit bold.

**Comment by pepeiborra** [comment]
After applying this change `--share-list` thinks that all the directories in our shared cache are failing with the same error, and yet the shared cache seems to work fine:
```
Directory: /apps/strats/forge/snapshotCache/.shake.cache/1000c52a4649de5b
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/1005770c1f3fcb9f
Warning: loadSharedCloud, couldn't find map for "FileQ {6d79ecbc53e9f565}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/1006fd4d77e2ff45
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/100a86b3f1f9b272
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/101f18810522cafa
Warning: loadSharedCloud, couldn't find map for "FileQ {6d79ecbc53e9f565}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/1021e8e7a88169c8
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/1023c43e36edeab9
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/10293fb837ddf319
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/102b98831265beac
Warning: loadSharedCloud, couldn't find map for "FileQ {6d79ecbc53e9f565}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/10307c8e74d97ddf
Warning: loadSharedCloud, couldn't find map for "FileQ {6d79ecbc53e9f565}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/10312c4d97bcb594
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/10314d10afc69826
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/1038352be87acc43
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/1041179404ec73b4
Warning: loadSharedCloud, couldn't find map for "FileQ {6d79ecbc53e9f565}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/1044916310b2a35e
Warning: loadSharedCloud, couldn't find map for "FileQ {6d79ecbc53e9f565}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/1044c2e323c7cae2
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/104b91da751e156e
Warning: loadSharedCloud, couldn't find map for "FileQ {6d79ecbc53e9f565}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/1053adf13fab659a
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/105592f47038d885
Warning: loadSharedCloud, couldn't find map for "FileQ {6d79ecbc53e9f565}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/105b68209f501376
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/105d2345e90acecc
Warning: loadSharedCloud, couldn't find map for "FileQ {6d79ecbc53e9f565}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/1065ba907c1ac754
Warning: loadSharedCloud, couldn't find map for "FileQ {18dc6c55f257b8c}"
Directory: /apps/strats/forge/snapshotCache/.shake.cache/106834a7fc69f9a2
```

**Comment by pepeiborra** [comment]
Has the binary serialisation of Shake artifacts changed in HEAD vs v0.17.7 ? 
If it has changed in a non backwards compatible way, that would explain the errors.

**Comment by ndmitchell** [comment]
Given we are now handling all exceptions, do we still need the `SharedException` type? I'm less worried about catching everything as its running in response to an explicit user action, so less likely to be called programmatically.

I'm unaware of anything that would have changed between your version and HEAD, and if I do incompatible on-disk changes I do try and put them in the changelog, but there's a chance I missed it given this code is relatively new.

**Comment by pepeiborra** [comment]
I rebased my change on top of the v0.17.7 branch and can confirm that `--share-list` succeeds to read our cache, whereas it doesn't with HEAD. So if it's not a serialisation change, maybe something else ?

**Comment by ndmitchell** [comment]
Thanks - I've merged this into master. Would you like a new release based off it, or are you likely to continue to use the backported version for now? Happy to make the new release if it's useful, otherwise I'll incorporate it when I next release.

**Pull request merged**
