### PR TITLE
Autodeps should consider a rename as a write to the destination path

### PR DESCRIPTION
**Pull request by jacereda**
This is the fix I mentioned in #778 (hopefully, I'm not on linux right now and wrote it from memory).

### CODE REVIEW

**Comment by jacereda** [comment]
Wow, all builds broken, not bad for 2 lines ;)

**Comment by jacereda** [comment]
Could it be a problem in the CI setups?

**Comment by ndmitchell** [comment]
Yeah, I'd ignore the CI. It's been a bit flakey. I need to invest some time on it , but Travis is shutting down their open source version soon, so I need to migrate it away :(

**Comment by ndmitchell** [comment]
As for the code, looks good - thanks!

**Pull request merged**
